[package]
name = "lang"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "base"
path = "src/base.rs"

[[bin]]
name = "thread"
path = "src/thread.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8" 
stopwatch = "0.0.7"